#!/bin/bash

# ==============================================================================
# Post-Processing Wrapper
# Runs plot generation and architectural comparison.
# Note: generate_summary_report.py is INTENTIONALLY OMITTED here because it is 
# already called at the end of both run_full_flow.sh and run_baseline_flow.sh. 
# Running it again here would be redundant and potentially overwrite data.
# ==============================================================================

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo "================================================================="
echo "        STARTING POST-PROCESSING (PLOTS & COMPARISON)            "
echo "================================================================="

# 1. Generate all the plots using the existing robust wrapper
# It will put all plots in the CrocCante/plots/ directory.
bash "$SCRIPT_DIR/generate_plots.sh"

# 2. Run the architectural comparison
# This will read the JSON files generated by the two flows and print the table.
echo ""
echo "================================================================="
echo "              GENERATING ARCHITECTURAL COMPARISON                "
echo "================================================================="
python3 "$SCRIPT_DIR/compare_summaries.py"

echo ""
echo "[INFO] Post-processing completed successfully!"
